### Домашняя работа к Уроку 1
### Студент: Абрамов А.В.

In [51]:
import torch
import torchvision
from IPython import display
import numpy as np
import random
from torch.autograd import Variable

In [11]:
# Создайте случайный FloatTensor размера 3x4x5
a = torch.rand(3, 4, 5)
print(f'Тип тензора: {a.type()}')
print(f'Размерность тензора: {a.size()}')
print(f'Содержимое тензора:\n{a}')

Тип тензора: torch.FloatTensor
Размерность тензора: torch.Size([3, 4, 5])
Содержимое тензора:
tensor([[[0.2858, 0.9393, 0.8734, 0.2777, 0.9381],
         [0.1811, 0.7772, 0.8366, 0.4496, 0.6700],
         [0.3070, 0.3142, 0.6357, 0.5863, 0.3065],
         [0.6272, 0.9490, 0.6183, 0.4847, 0.9994]],

        [[0.8067, 0.4158, 0.5025, 0.4113, 0.9877],
         [0.7872, 0.3344, 0.8283, 0.8249, 0.4997],
         [0.4272, 0.4691, 0.7247, 0.1345, 0.5630],
         [0.6178, 0.3960, 0.2661, 0.2215, 0.7624]],

        [[0.2658, 0.1048, 0.0579, 0.7178, 0.1760],
         [0.0261, 0.3511, 0.8781, 0.5574, 0.9233],
         [0.4318, 0.3495, 0.0345, 0.9762, 0.9505],
         [0.7581, 0.2272, 0.1048, 0.9153, 0.5769]]])


In [13]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [29]:
# Приведите его к форме 6 X 10
b = a.reshape(6, 10)
b

tensor([[0.2858, 0.9393, 0.8734, 0.2777, 0.9381, 0.1811, 0.7772, 0.8366, 0.4496,
         0.6700],
        [0.3070, 0.3142, 0.6357, 0.5863, 0.3065, 0.6272, 0.9490, 0.6183, 0.4847,
         0.9994],
        [0.8067, 0.4158, 0.5025, 0.4113, 0.9877, 0.7872, 0.3344, 0.8283, 0.8249,
         0.4997],
        [0.4272, 0.4691, 0.7247, 0.1345, 0.5630, 0.6178, 0.3960, 0.2661, 0.2215,
         0.7624],
        [0.2658, 0.1048, 0.0579, 0.7178, 0.1760, 0.0261, 0.3511, 0.8781, 0.5574,
         0.9233],
        [0.4318, 0.3495, 0.0345, 0.9762, 0.9505, 0.7581, 0.2272, 0.1048, 0.9153,
         0.5769]])

In [54]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
c = torch.FloatTensor([1, 4, 2, 2, 1, 1, 4, 2, 2, 1])
d = b * c
d

tensor([[0.2858, 3.7572, 1.7468, 0.5554, 0.9381, 0.1811, 3.1089, 1.6733, 0.8991,
         0.6700],
        [0.3070, 1.2569, 1.2714, 1.1726, 0.3065, 0.6272, 3.7961, 1.2365, 0.9695,
         0.9994],
        [0.8067, 1.6631, 1.0049, 0.8227, 0.9877, 0.7872, 1.3377, 1.6565, 1.6498,
         0.4997],
        [0.4272, 1.8764, 1.4493, 0.2690, 0.5630, 0.6178, 1.5841, 0.5321, 0.4430,
         0.7624],
        [0.2658, 0.4192, 0.1158, 1.4355, 0.1760, 0.0261, 1.4046, 1.7561, 1.1147,
         0.9233],
        [0.4318, 1.3979, 0.0690, 1.9524, 0.9505, 0.7581, 0.9088, 0.2097, 1.8307,
         0.5769]])

In [43]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
j = d.mm(d.reshape(10, 6))
j

tensor([[22.2831, 16.4366,  9.0472, 10.1095, 14.7257, 14.3553],
        [15.5059, 12.7849,  7.5471,  8.9276, 12.1794, 10.9447],
        [13.4129, 15.0608,  8.3891,  8.8829, 11.6925, 12.1149],
        [12.6683, 10.9092,  6.4227,  5.9504, 10.6203,  8.0154],
        [ 7.6516,  8.4557,  4.5599,  6.0558,  7.1726,  8.3851],
        [11.7653, 11.0763,  7.7318,  9.6235,  6.7717,  9.1262]])

In [48]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)

y = x ** 3 + z - 75 * t
y.backward()

print(f'd(y)/d(x)={x.grad.item()}')
print(f'd(y)/d(z)={z.grad.item()}')
print(f'd(y)/d(t)={t.grad.item()}')

d(y)/d(x)=3.0
d(y)/d(z)=1.0
d(y)/d(t)=-75.0


In [49]:
# Создайте единичный тензор размера 5x6
n = torch.eye(5,6)
n

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

In [50]:
# Переведите его в формат numpy
n.numpy()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)

In [52]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
def function(x, w1):
    return x**w1 - 2 * x**2 + 5

def gradient(x):
    return torch.autograd.grad(function(x, w1), x)[0]

w1 = 3
x = Variable(torch.Tensor([2]), requires_grad=True)
learning_rate = 0.01
num_iterations = 120
for i in range(num_iterations):
    x_grad = gradient(x)
    x.data -= learning_rate * x_grad
    if not i%10:
        print(f"Iteration {i+1}, x = {x.data[0]:.2f}, y = {function(x.data[0], w1):.2f}")

Iteration 1, x = 1.96, y = 4.85
Iteration 11, x = 1.69, y = 4.12
Iteration 21, x = 1.55, y = 3.92
Iteration 31, x = 1.47, y = 3.85
Iteration 41, x = 1.42, y = 3.83
Iteration 51, x = 1.39, y = 3.82
Iteration 61, x = 1.37, y = 3.82
Iteration 71, x = 1.36, y = 3.82
Iteration 81, x = 1.35, y = 3.82
Iteration 91, x = 1.34, y = 3.82
Iteration 101, x = 1.34, y = 3.81
Iteration 111, x = 1.34, y = 3.81
